const dataArray = [
    {
      Photo: null,
      address: "123 Main St",
      adharCard: "1234-5678-9012",
      adharCardFile: null,
      disease: true,
      diseaseFile: null,
      district: "District1",
      dob: "1990-01-01",
      email: "example1@example.com",
      fatherName: "John Doe",
      gotra: "Gotra1",
      maritalStatus: "Single",
      mobile: "1234567890",
      motherName: "Jane Doe",
      name: "Alice Smith",
      nominee1: { name: "Bob Smith", relationship: "Brother" },
      nominee2: { name: "Carol Smith", relationship: "Sister" },
      otp: "123456",
      password: "password1",
      pincode: "123456",
      profession: "Engineer",
      referenceId: "REF123",
      rulesAccepted: true,
      spouseName: "",
      state: "State1",
      voterId: "VOTER123456",
      voterIdFile: null,
    },
    {
      Photo: null,
      address: "456 Elm St",
      adharCard: "2345-6789-0123",
      adharCardFile: null,
      disease: false,
      diseaseFile: null,
      district: "District2",
      dob: "1985-05-15",
      email: "example2@example.com",
      fatherName: "Michael Johnson",
      gotra: "Gotra2",
      maritalStatus: "Married",
      mobile: "2345678901",
      motherName: "Sarah Johnson",
      name: "David Brown",
      nominee1: { name: "Emily Brown", relationship: "Wife" },
      nominee2: { name: "Michael Brown", relationship: "Son" },
      otp: "654321",
      password: "password2",
      pincode: "654321",
      profession: "Doctor",
      referenceId: "REF456",
      rulesAccepted: true,
      spouseName: "Emily Brown",
      state: "State2",
      voterId: "VOTER654321",
      voterIdFile: null,
    },
    {
      Photo: null,
      address: "789 Pine St",
      adharCard: "3456-7890-1234",
      adharCardFile: null,
      disease: true,
      diseaseFile: null,
      district: "District3",
      dob: "1980-08-20",
      email: "example3@example.com",
      fatherName: "Robert Lee",
      gotra: "Gotra3",
      maritalStatus: "Widowed",
      mobile: "3456789012",
      motherName: "Linda Lee",
      name: "Emily Clark",
      nominee1: { name: "James Clark", relationship: "Brother" },
      nominee2: { name: "Laura Clark", relationship: "Sister" },
      otp: "987654",
      password: "password3",
      pincode: "987654",
      profession: "Teacher",
      referenceId: "REF789",
      rulesAccepted: false,
      spouseName: "",
      state: "State3",
      voterId: "VOTER987654",
      voterIdFile: null,
    },
    {
      Photo: null,
      address: "321 Oak St",
      adharCard: "4567-8901-2345",
      adharCardFile: null,
      disease: false,
      diseaseFile: null,
      district: "District4",
      dob: "1992-12-12",
      email: "example4@example.com",
      fatherName: "John Smith",
      gotra: "Gotra4",
      maritalStatus: "Single",
      mobile: "4567890123",
      motherName: "Alice Smith",
      name: "Michael Johnson",
      nominee1: { name: "Sarah Johnson", relationship: "Wife" },
      nominee2: { name: "Robert Johnson", relationship: "Son" },
      otp: "321654",
      password: "password4",
      pincode: "321654",
      profession: "Architect",
      referenceId: "REF012",
      rulesAccepted: true,
      spouseName: "Sarah Johnson",
      state: "State4",
      voterId: "VOTER321654",
      voterIdFile: null,
    },
    {
      Photo: null,
      address: "654 Maple St",
      adharCard: "5678-9012-3456",
      adharCardFile: null,
      disease: true,
      diseaseFile: null,
      district: "District5",
      dob: "1978-11-30",
      email: "example5@example.com",
      fatherName: "Richard King",
      gotra: "Gotra5",
      maritalStatus: "Divorced",
      mobile: "5678901234",
      motherName: "Emily King",
      name: "Sarah White",
      nominee1: { name: "Laura White", relationship: "Daughter" },
      nominee2: { name: "Daniel White", relationship: "Son" },
      otp: "789012",
      password: "password5",
      pincode: "789012",
      profession: "Writer",
      referenceId: "REF345",
      rulesAccepted: false,
      spouseName: "",
      state: "State5",
      voterId: "VOTER789012",
      voterIdFile: null,
    }
  ];
  
  export default dataArray;
  